DROP DATABASE IF EXISTS 'factory';
CREATE DATABASE IF NOT EXISTS 'factory';
USE 'factory';

-- 创建表结构
-- 表名和字段名外面的符号 ` 不是单引号，而是英文输入法状态下的反单引号，也就是键盘左上角 esc 按键下面的那一个 ~ 按键

CREATE TABLE `t_node` (
  `GSZCM` VARCHAR(100) NOT NULL PRIMARY KEY COMMENT '工商注册码',
  `DWBM` VARCHAR(100)  COMMENT '单位编码',
  `DWDM` VARCHAR(100) COMMENT '单位代码',
  `DWMC` VARCHAR(100) COMMENT '单位名称',
  `IP` VARCHAR(64) COMMENT '单位ip地址',
  `PORT` VARCHAR(10) COMMENT '端口',
  `YWLXBM`VARCHAR(50) COMMENT '节点业务类型',
  `BZ` VARCHAR(200) COMMENT '备注',
  `BGSJ` TIMESTAMP  COMMENT '变更时间'
)DEFAULT CHARSET=utf8mb4 COMMENT='节点表';

CREATE TABLE `t_business_type`(
  `LXBM` VARCHAR(50) NOT NULL PRIMARY KEY COMMENT '类型编码',
  `LXMS` VARCHAR(100) COMMENT '类型描述',
  `GSHY` VARCHAR(20) COMMENT '产品归属行业'
)DEFAULT CHARTSET=utf8mb4 COMMENT '业务类型表';

CREATE TABLE `t_station`(
  `GWBM` VARCHAR(100) NOT NULL PRIMARY KEY COMMENT '岗位编码',
  `JDBM` VARCHAR(50) COMMENT '节点唯一码',
  `GWMC` VARCHAR(100) COMMENT '岗位名称',
  `YWLXBM` VARCHAR(50) COMMENT '岗位业务类型',
  `SFQY` INT(2) COMMENT '是否启用',
  `BZ` VARCHAR(200) COMMENT '备注',
  `BGSJ` TIMESTAMP  COMMENT '变更时间'
)DEFAULT CHARSET=utf8mb4 COMMENT '岗位表';

CREATE TABLE `t_limit`(
  `QXBM` VARCHAR(100) NOT NULL PRIMARY KEY COMMENT '权限编码',
  `QXMS` VARCHAR(100) COMMENT '权限描述',
  `JDBM` VARCHAR(50) COMMENT '节点唯一码'
)DEFAULT CHARSET=utf8mb4 COMMENT '权限表';

CREATE TABLE `t_station_limit`(
  `GWBM` VARCHAR(100) NOT NULL COMMENT '岗位编码',
  `QXBM` VARCHAR(100) NOT NULL COMMENT '权限编码',
  `JDBM` VARCHAR(50) COMMENT '节点唯一码'
)DEFAULT CHARSET=utf8mb4 COMMENT '岗位权限表';

CREATE TABLE `t_employee`(
  `YGBM` VARCHAR(100) NOT NULL PRIMARY KEY COMMENT '员工编码',
  `YGXM` VARCHAR(20) NOT NULL COMMENT '员工姓名',
  `YGXB` INT(2)  COMMENT '员工性别',
  `YGMM` VARCHAR(20)  COMMENT '员工密码',
  `CSRQ` DATE  COMMENT '出生日期',
  `LXDH` VARCHAR(20) COMMENT '联系电话',
  `LXYX` VARCHAR(30) COMMWNT '联系邮箱',
  `RZSJ` DATE COMMENT '入职时间',
  `LZSJ` DATE COMMENT '离职时间',
  `JDBM` VARCHAR(50) COMMENT '节点唯一码'
)DEFAULT CHARSET=utf8mb4 COMMENT '员工表';

CREATE TABLE `t_employee_station`(
  `GWBM` VARCHAR(100) NOT NULL COMMENT '岗位编码',
  `YGBM` VARCHAR(100) NOT NULL COMMENT '员工编码',
  `JDBM` VARCHAR(50) COMMENT '节点唯一码'
)DEFAULT CHARSET=utf8mb4 COMMENT '员工岗位表';

CREATE TABLE `t_login_record`(
  `YGBM` VARCHAR(100) COMMENT '员工编码',
  `DLSJ` TIMESTAMP COMMENT '登录时间',
  `TCSJ` TIMESTAMP COMMENT '退出时间'
)DEFAULT CHARSET=utf8mb4 COMMENT '员工登录记录表';

CREATE TABLE `t_product`(
  `CPXH` VARCHAR(200) NOT NULL PRIMARY KEY COMMENT '产品型号',
  `CPMS` VARCHAR(200) COMMENT '产品描述',
  `JLDW` VARCHAR(10) COMMENT '计量单位',
  `CKJG` DOUBLE COMMENT '参考价格',
  `SCCJ` VARCHAR(100) COMMENT '生产厂家',
  `BZ` VARCHAR(200) COMMENT '备注',
  `BGSJ` TIMESTAMP  COMMENT '变更时间',
  `CZCP` VARCHAR(200) COMMENT '参照产品',
  `YWLXBM` VARCHAR(50) COMMENT '产品类型编码',
  `JDBM` VARCHAR(50) COMMENT '节点唯一码'
)DEFAULT CHARSET=utf8mb4 COMMENT '产品基础表';

CREATE TABLE `t_product_replace`(
  `CPXH` VARCHAR(200) COMMENT '产品型号',
  `THCPXH` VARCHAR(200) COMMENT '替换产品型号',
  `FLBM` VARCHAR(200) COMMENT '分类编码',
  `THFLBM` VARCHAR(200) COMMENT '替换分类编码'
)DEFAULT CHARSET=utf8mb4 COMMENT '产品替换表';

CREATE TABLE `t_category`(
  `LBBM` VARCHAR(20) NOT NULL PRIMARY KEY COMMENT '类别编码',
  `LBMC` VARCHAR(50) COMMENT '类别名称',
  `BZ` VARCHAR(200) COMMENT '备注',
  `BGSJ` TIMESTAMP  COMMENT '变更时间'
)DEFAULT CHARSET=utf8mb4 COMMENT '类别(产品)表';

CREATE TABLE `t_property`(
  `LBBM` VARCHAR(50) COMMENT '归属类别编码',
  `SXMC` VARCHAR(20)  COMMENT '属性名称',
  `BZ` VARCHAR(200) COMMENT '备注',
  `BGSJ` TIMESTAMP  COMMENT '变更时间'
)DEFAULT CHARSET=utf8mb4 COMMENT '属性表';

CREATE TABLE `t_product_category`(
  `CPXH` VARCHAR(200) COMMENT '产品型号',
  `LBBM` VARCHAR(20) COMMENT '类别编码',
  `SXBM` VARCHAR(20) COMMENT '属性编码',
  `BZ` VARCHAR(200) COMMENT '备注',
  `BGSJ` TIMESTAMP  COMMENT '变更时间'
)DEFAULT CHARSET=utf8mb4 COMMENT '产品分类表';

CREATE TABLE `t_state`(
  `ZTBM` VARCHAR(10) NOT NULL PRIMARY KEY COMMENT '状态码',
  `ZTSM` VARCHAR(20) COMMENT '状态说明',
  `BZ` VARCHAR(200) COMMENT '备注',
  `BGSJ` TIMESTAMP  COMMENT '变更时间'
)DEFAULT CHARSET=utf8mb4 COMMENT '状态表';

CREATE TABLE `t_message`(
  `id` INT(18) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `FSJDBM` VARCHAR(100) COMMENT '发送节点编码',
  `FSGWBM` VARCHAR(100) COMMENT '发送岗位编码',
  `JSJDBM` VARCHAR(100) COMMENT '接收节点编码',
  `JSGWBM` VARCHAR(100) COMMENT '接收岗位编码',
  `GLBM` VARCHAR(20) COMMENT '关联表名',
  `GLID` VARCHAR(100) COMMENT '关联id',
  `TZBT` VARCHAR(100) COMMENT '通知标题',
  `TZNR` VARCHAR(300) COMMENT '通知内容',
  `TZLX` VARCHAR(20) COMMENT '通知类型',
  `BZ` VARCHAR(200) COMMENT '备注',
  `BGSJ` TIMESTAMP  COMMENT '变更时间'
)DEFAULT CHARSET=utf8mb4 COMMENT '通知消息表';

CREATE TABLE `t_product_struction`(
  `id` INT(18) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `CPXH` VARCHAR(100) COMMENT '产品型号',
  `FLBM` VARCHAR(100) COMMENT '产品分类编码',
  `URL` VARCHAR(300) COMMENT '文件地址',
  `WLMC` VARCHAR(40) COMMENT '文件名称',
  `WLMS` VARCHAR(200) COMMENT '文件描述',
  `BZ` VARCHAR(200) COMMENT '备注',
  `BGSJ` TIMESTAMP  COMMENT '变更时间'
)DEFAULT CHARSET=utf8mb4 COMMENT '产品指导书表';

CREATE TABLE `t_struction_relation`(
  `id` INT(18) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `GLBM` VARCHAR(20) COMMENT '关联表名',
  `GLID` VARCHAR(100) COMMENT '关联id',
  `ZDSID` VARCHAR(100) COMMENT '指导书id',
)DEFAULT CHARSET=utf8mb4 COMMENT '指导书相关表';

CREATE TABLE `t_show_text`(
  `id` INT(18) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `ZDBM` VARCHAR(10) COMMENT '字段名',
  `XSWZ` VARCHAR(20) COMMENT '显示文字',
  `BZ` VARCHAR(200) COMMENT '备注'
)DEFAULT CHARSET=utf8mb4 COMMENT '页面文字显示表';

CREATE TABLE `t_process`(
  `id` INT(18) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `LXBM` VARCHAR(100) COMMENT '产品类型编码',
  `CPXH` VARCHAR(100) COMMENT '产品型号',
  `FLBM` VARCHAR(100) COMMENT '分类编码',
  `GXMS` VARCHAR(100) COMMENT '工序描述',
  `GSXS` INT(4) COMMENT '工时系数',
  `GXLXBM` VARCHAR(100) COMMENT '工序类型编码',
  `JDBM` VARCHAR(100) COMMENT '归属节点编码',
  `SFCS` INT(2) COMMENT '是否为初始工序',
  `SCCPXH` VARCHAR(100) COMMENT '输出产品型号',
  `SCCPMS` VARCHAR(100) COMMENT '输出产品描述',
  `SCFLMS` VARCHAR(100) COMMENT '输出分类描述',
  `SCSL` INT(10) COMMENT '输出数量',
  `SCCL` INT(10) COMMENT '输出初料',
  `BGSJ` TIMESTAMP  COMMENT '变更时间'
)DEFAULT CHARSET=utf8mb4 COMMENT '产品工序基础表';

CREATE TABLE `t_process_relation`(
  `id` INT(18) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `GXID` INT(18) COMMENT '工序id',
  `HGXID` INT(18) COMMENT '后工序id'
)DEFAULT CHARSET=utf8mb4 COMMENT '工序关系表';

CREATE TABLE `t_process_bom`(
  `id` INT(18) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `CPLXBM` VARCHAR(100) COMMENT '产品类型编码',
  `CSRWID` INT(18) COMMENT '初始任务id',
  `GXID` INT(18) COMMENT '工序id',
  `WLXH` VARCHAR(100) COMMENT '物料型号',
  `WLFLBM` VARCHAR(100) COMMENT '物料分类编码',
  `WLDH` INT(10) COMMENT '物料单耗',
  `WLLY` VARCHAR(10) COMMENT '物料来源',
  `BZ` VARCHAR(200) COMMENT '备注',
  `BGSJ` TIMESTAMP  COMMENT '变更时间'
)DEFAULT CHARSET=utf8mb4 COMMENT '工序物料表';

